<?php

use Drupal\editor\Entity\Editor;

/**
 * @file
 * Contains project_backend.module.
 */

// Custom admin css.
Drupal::moduleHandler()
  ->loadInclude('project_backend', 'inc', 'project_backend.theme');

// Add remote audio as a media type.
Drupal::moduleHandler()
  ->loadInclude('project_backend', 'inc', 'project_backend.media_types');


/**
 * Load our theme's CK Editor CSS file.
 *
 * Implements hook_ckeditor_css_alter().
 */
function project_backend_ckeditor_css_alter(array &$css, Editor $editor) {
  $css[] = Drupal::service('extension.list.theme')
      ->getPath('nrgi') . '/assets/css/ckeditor-style.css';
}

function project_backend_language_switch_links_alter(array &$links, $type, $path) {
  $translationLanguages = Drupal::routeMatch()->getParameter('node')->getTranslationLanguages();
  foreach ($links as $lang => $link) {
    if (!in_array($lang, array_keys($translationLanguages))) {
      unset($links[$lang]);
    }
  }
}
