<?php

/**
 * @file
 * Contains nrgi_frontend.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

\Drupal::moduleHandler()->loadInclude('nrgi_frontend', 'inc', 'nrgi_frontend.field');
\Drupal::moduleHandler()->loadInclude('nrgi_frontend', 'inc', 'nrgi_frontend.form');
\Drupal::moduleHandler()->loadInclude('nrgi_frontend', 'inc', 'nrgi_frontend.meta');
\Drupal::moduleHandler()->loadInclude('nrgi_frontend', 'inc', 'nrgi_frontend.metatag');
\Drupal::moduleHandler()->loadInclude('nrgi_frontend', 'inc', 'nrgi_frontend.node');
\Drupal::moduleHandler()->loadInclude('nrgi_frontend', 'inc', 'nrgi_frontend.region');
\Drupal::moduleHandler()->loadInclude('nrgi_frontend', 'inc', 'nrgi_frontend.paragraph');
\Drupal::moduleHandler()->loadInclude('nrgi_frontend', 'inc', 'nrgi_frontend.views');
